version: '3.1'

services:

  mongo:
    image: mongo:3.6
    container_name: recipesdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - './data/mongo:/data/db'
    ports:
      - 27017:27017
    networks:
      - recipenetwork

networks:
  recipenetwork:
    ipam:
      driver: default
      config:
        - subnet: 6.6.6.0/24
