name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Start MongoDB
      run:  sudo docker run --name recipesdb -d -p 27017:27017 mongo \
       -e MONGO_INITDB_ROOT_USERNAME=root \
       -e MONGO_INITDB_ROOT_PASSWORD=toor \
    
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Test
      run: go test ./...
